name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          cache-dependency-path: sdk/package-lock.json
      - run: npm ci
      - run: chmod +x ./build/bin/myback-sdk-cli.js
      - run: npm link
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  public-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: sdk/package-lock.json
      - run: npm ci
      - name: Generate docs
        run: npm run docs
      - name: Upload docs
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          dangerous-clean-slate: true
          local-dir: ./sdk/out/
          server: ftp.skiesoft.com
          username: myback-sdk-docs@skiesoft.com
          password: ${{ secrets.DOCS_FTP_PASSWORD }}
