name: Test API Tester

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./api-tester

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: api-tester/package-lock.json
    - name: Install dependencies.
      run: npm ci
    - name: Build NPM package.
      run: npm run build --if-present
    - name: Run testsuits.
      run: npm test

    - name: Archive npm failure logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: npm-logs
        path: ~/.npm/_logs
