name: Test SDK

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./sdk

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: sdk/package-lock.json
    - name: Install ts-node globally.
      run: npm i -g ts-node
    - name: Install dependencies and build package.
      run: npm ci
    - name: Make CLI executable.
      run: chmod +x ./build/bin/myback-sdk-cli.js
    - name: Link CLI.
      run: npm link
    - name: Run testsuits.
      run: npm test
      env:
        API_TOKEN: ${{secrets.api_token}}
        DATABASE_ID: ${{secrets.database_id}}
        STORAGE_ID: ${{secrets.storage_id}}

    - name: Archive npm failure logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: npm-logs
        path: ~/.npm/_logs
