env:
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.test.json
rules: {
  '@typescript-eslint/no-floating-promises': off
}
